name: Rust CI

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
    tags: ["*"]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

permissions:
  contents: read

jobs:
  deps:
    name: Unused Dependencies
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v7
      - name: Check for unused dependencies
        uses: bnjbvr/cargo-machete@main

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use Rust/Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Build docs
        run: nix develop --command just doc

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check format
        run: nix develop --command just format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use Rust/Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Run Clippy
        run: nix develop --command just lint

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Use Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use Rust/Cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Build project
        run: nix develop --command just build
      - name: Test project
        run: nix develop --command just test
